### ISSUE TITLE
Peer miller-rabin@1.1.2 wants bn.js@^0.16.0

### ISSUE THREAD

**Issue by barneycarroll** [calvinmetcalf/diffie-hellman#5]

**Comment by mchlbrnd** [comment]
https://github.com/guybedford/diffie-hellman/commit/d865eaa02878e18582ae0db1fb6f6556da6c53d0

**Comment by AlexGalays** [comment]
Just when I deleted node_modules, npm install again :)

**Comment by j0hnsmith** [comment]
I see the same, please push fix to npm.

**Comment by pluma** [comment]
+1

browserify has a deep dependency on this package, so this bug is currently affecting anyone trying to install browserify :/

**Comment by rhalff** [comment]
+1 never heard of this package yet my code is failing :-)

**Comment by mstefaniuk** [comment]
+1

**Comment by p3k** [comment]
+1

**Comment by rhalff** [comment]
I'll star the package just to pay gratitude to it's relevance.. ;-)

**Comment by TiddoLangerak** [comment]
For anyone having this problem, you can temporary work around this problem by installing `miller-rabin@1.1.1` as a peer-dependency in your own project (`npm install miller-rabin@1.1.1 --save-peer`). This ensures `bn.js@0.15` is used.

**Comment by hugofqueiros** [comment]
+1

**Comment by jnoleau** [comment]
+1

**Comment by calvinmetcalf** [comment]
Will fix all these this evening or first thing tommorow

**Comment by sergeyzenchenko** [comment]
+1

**Comment by paulreeve** [comment]
+1

**Comment by marcio** [comment]
+1

**Comment by andreitr** [comment]
+1

**Comment by DavidSouther** [comment]
@calvinmetcalf Your package is so deep in the dependency list, this issue is causing hell for basically anyone trying to do anything with Browserify and several others. Please either take time to fix (should be as easy as merging one of the three open PRs) and publishing, or granthing authority on this repo and npmjs for another to do so.

**Comment by mchlbrnd** [comment]
@DavidSouther +1

**Comment by cwonrails** [comment]
+1

**Comment by gautamarora** [comment]
+1 thanks for the temporary work around @TiddoLangerak

**Comment by thetutlage** [comment]
Got up working great https://github.com/indutny/miller-rabin/commit/bb85f555974587a410a17173f0bc484133b53cb7

**Comment by DavidSouther** [comment]
Good news everyone! This issue has been fixed downstream! It can now be closed! Thanks for jumping on it, @indutny!

**Comment by cwonrails** [comment]
Awesome, thanks @indutny!

**Comment by barneycarroll** [comment]
Nice, thanks @TiddoLangerak for pointing this out.

**Comment by AlexGalays** [comment]
![image](https://cloud.githubusercontent.com/assets/1375586/5597806/754d1b46-92a9-11e4-9612-493afaec166d.png)

**Comment by Kagami** [comment]
![2823171-we_did_it](https://cloud.githubusercontent.com/assets/533383/5597851/1a5993d8-92bb-11e4-9c98-a1948e9060aa.jpg)

**Comment by thetutlage** [comment]
It is causing issue again on installing packages globally 
Peer miller-rabin@1.1.2 wants bn.js@^0.16.0

**Comment by indutny** [comment]
@thetutlage it is 1.1.4 now, please clear your cache.

**Comment by calvinmetcalf** [comment]
sorry for this, was literally at the airport about to get on  plain when this was raised.  This plain, mind you, after take off had a flap problem and had to land but first had to spend several hours burning off fuel by flying in circles before relanding at the airport we took off from.  Thank you to all that fixed this while I was  circling the Atlantic specifically @guybedford and @indutny

**Comment by indutny** [comment]
Glad that everything is fine.

**Comment by DavidSouther** [comment]
Hah, talk about perfect worst timing! We always used to joke about key devs getting hit by a bus, but I'll have to add this scenario to a disaster prep plan!
